name: Update GitHub Streak

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/streak-stats.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate streak statistics
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=dark&hide_border=true&ring=1E6FDB&fire=1E6FDB&currStreakLabel=1E6FDB&sideLabels=FFFFFF&dates=AAAAAA&currStreakNum=FFFFFF&sideNums=FFFFFF&background=00000000
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak statistics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update GitHub streak statistics" || exit 0
          git push
